# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    - name: Docker Login
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER-PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: 
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - name: Docker Push
      env:
        REPO: java-gradle
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest ${{secrets.DOCKER_USERNAME}}/$REPO:latest
        docker push ${{secrets.DOCKER_USER}}/$REPO
    
    - name: Docker Pull & Run From Hub
      uses: appleboy/ssh-action@master
      with:
        host: ip-172-31-54-162.ec2.internal
        username: ec2-user
        key: ${{secrets.PRIVATE_KEY}}
        envs: GITHUB_SHA
        script: |
          docker login
          docker pull ${{secrets.DOCKER_USER}}/$REPO
          docker stop backend_server
          docker rm backednd_server 
          docker run --detach --name backend_server -p 80:8080 devops115/java-gradle
          
